# Generated by Django 3.2.16 on 2022-12-19 12:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('ordered', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='slug', editable=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='images/categories')),
                ('show', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('vk', 'Vk'), ('youtube', 'Youtube'), ('avito', 'Avito')], max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(unique=True)),
                ('code', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cart_amounts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), blank=True, default=list, size=None)),
                ('cart', models.ManyToManyField(blank=True, to='main.Amount')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/infopages')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('privacy_policy', models.FileField(null=True, upload_to='documents')),
                ('terms_of_use', models.FileField(null=True, upload_to='documents')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='images/title')),
                ('main_caterories', models.ManyToManyField(to='main.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(limit_choices_to={'is_leaf': True}, on_delete=django.db.models.deletion.PROTECT, to='main.category')),
                ('images', models.ManyToManyField(blank=True, to='main.ProductImage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('title_image', models.ImageField(upload_to='images/products')),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=10)),
                ('show', models.BooleanField(default=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('amounts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('date', models.DateTimeField()),
                ('delivery', models.TextField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.customuser')),
                ('products', models.ManyToManyField(to='main.Amount')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='slug', editable=False)),
                ('title', models.CharField(max_length=20)),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='images/infopages')),
                ('text_area_1', models.TextField()),
                ('text_area_2', models.TextField(blank=True, null=True)),
                ('images', models.ManyToManyField(blank=True, to='main.InfoPageImage')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='main.Product'),
        ),
        migrations.AddField(
            model_name='amount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product'),
        ),
    ]
