# Generated by Django 3.2.16 on 2022-12-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms_of_use',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/title'),
        ),
    ]
