# Generated by Django 3.2.16 on 2022-12-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221219_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart_amounts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='old_cart',
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='main.amount'),
        ),
    ]
