# Generated by Django 3.2.16 on 2022-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('privacy_policy', models.FileField(null=True, upload_to='documents')),
                ('terms_of_use', models.FileField(null=True, upload_to='documents')),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='images/title')),
                ('main_caterories', models.ManyToManyField(to='main.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
