# Generated by Django 3.2.16 on 2022-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='public_name',
            field=models.CharField(max_length=50),
        ),
    ]
